2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Configure stats pid to 10752
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Loading settings from C:\Users\BHARGAV BADE\.config\wandb\settings
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Loading settings from C:\Users\BHARGAV BADE\Multivar LSTM\wandb\settings
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'train_test_sng_step.py', 'program_abspath': 'c:\\users\\bhargav bade\\multivar lstm\\train_test_sng_step.py', 'program': 'c:\\users\\bhargav bade\\multivar lstm\\train_test_sng_step.py'}
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-25 23:26:14,924 ERROR   MainThread:10752 [wandb_setup.py:_flush():81] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 473, in exec_code
    exec_fun(compile(ast_code, filename, 'exec'), ns_globals, ns_locals)
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
  File "c:\users\bhargav bade\multivar lstm\train_test_sng_step.py", line 186, in <module>
    #Train the model
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\sdk\wandb_init.py", line 1270, in init
    wandb._sentry.reraise(e)
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\analytics\sentry.py", line 161, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\sdk\wandb_init.py", line 1255, in init
    wi.setup(kwargs)
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\sdk\wandb_init.py", line 304, in setup
    wandb_login._login(
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\sdk\wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\sdk\wandb_login.py", line 281, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_init.py:_log_setup():533] Logging user logs to C:\Users\BHARGAV BADE\Multivar LSTM\wandb\run-20241125_232614-9nkqnk49\logs\debug.log
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_init.py:_log_setup():534] Logging internal logs to C:\Users\BHARGAV BADE\Multivar LSTM\wandb\run-20241125_232614-9nkqnk49\logs\debug-internal.log
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_init.py:init():619] calling init triggers
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'epochs': 20, 'bs': 32, 'lr': 0.001, 'num_layers': 3, 'latent size': 64}
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_init.py:init():669] starting backend
2024-11-25 23:26:14,924 INFO    MainThread:10752 [wandb_init.py:init():673] sending inform_init request
2024-11-25 23:26:14,936 INFO    MainThread:10752 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-11-25 23:26:14,937 INFO    MainThread:10752 [wandb_init.py:init():686] backend started and connected
2024-11-25 23:26:14,944 INFO    MainThread:10752 [wandb_init.py:init():781] updated telemetry
2024-11-25 23:26:15,017 INFO    MainThread:10752 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-25 23:26:17,356 INFO    MainThread:10752 [wandb_init.py:init():867] starting run threads in backend
2024-11-25 23:26:17,946 INFO    MainThread:10752 [wandb_run.py:_console_start():2456] atexit reg
2024-11-25 23:26:17,946 INFO    MainThread:10752 [wandb_run.py:_redirect():2305] redirect: wrap_raw
2024-11-25 23:26:17,947 INFO    MainThread:10752 [wandb_run.py:_redirect():2370] Wrapping output streams.
2024-11-25 23:26:17,947 INFO    MainThread:10752 [wandb_run.py:_redirect():2395] Redirects installed.
2024-11-25 23:26:17,948 INFO    MainThread:10752 [wandb_init.py:init():911] run started, returning control to user process
2024-11-25 23:35:25,997 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-11-25 23:35:25,997 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Configure stats pid to 10752
2024-11-25 23:35:25,997 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Loading settings from C:\Users\BHARGAV BADE\.config\wandb\settings
2024-11-25 23:35:25,997 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Loading settings from C:\Users\BHARGAV BADE\Multivar LSTM\wandb\settings
2024-11-25 23:35:25,998 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-25 23:35:25,998 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-25 23:35:25,998 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'train_test_sng_step.py', 'program_abspath': 'c:\\users\\bhargav bade\\multivar lstm\\train_test_sng_step.py', 'program': 'c:\\users\\bhargav bade\\multivar lstm\\train_test_sng_step.py'}
2024-11-25 23:35:25,998 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-25 23:35:25,998 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-11-25 23:35:25,998 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Applying login settings: {'api_key': '***REDACTED***'}
2024-11-25 23:35:25,998 INFO    MainThread:10752 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-25 23:35:25,998 ERROR   MainThread:10752 [wandb_setup.py:_flush():81] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 473, in exec_code
    exec_fun(compile(ast_code, filename, 'exec'), ns_globals, ns_locals)
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
  File "c:\users\bhargav bade\multivar lstm\train_test_sng_step.py", line 186, in <module>
    #Train the model
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\sdk\wandb_init.py", line 1270, in init
    wandb._sentry.reraise(e)
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\analytics\sentry.py", line 161, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\sdk\wandb_init.py", line 1255, in init
    wi.setup(kwargs)
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\sdk\wandb_init.py", line 304, in setup
    wandb_login._login(
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\sdk\wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "C:\Users\BHARGAV BADE\miniconda3\envs\pyda3.9\lib\site-packages\wandb\sdk\wandb_login.py", line 281, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
2024-11-25 23:35:26,000 INFO    MainThread:10752 [wandb_init.py:_log_setup():533] Logging user logs to C:\Users\BHARGAV BADE\Multivar LSTM\wandb\run-20241125_233525-zuor8qp7\logs\debug.log
2024-11-25 23:35:26,000 INFO    MainThread:10752 [wandb_init.py:_log_setup():534] Logging internal logs to C:\Users\BHARGAV BADE\Multivar LSTM\wandb\run-20241125_233525-zuor8qp7\logs\debug-internal.log
2024-11-25 23:35:26,000 INFO    MainThread:10752 [wandb_init.py:init():619] calling init triggers
2024-11-25 23:35:26,000 INFO    MainThread:10752 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'epochs': 20, 'bs': 32, 'lr': 0.001, 'num_layers': 3, 'latent size': 64}
2024-11-25 23:35:26,000 INFO    MainThread:10752 [wandb_init.py:init():664] wandb.init() called when a run is still active
2024-11-25 23:40:11,270 WARNING MsgRouterThr:10752 [router.py:message_loop():75] message_loop has been closed
